version: "3.8"
services:
  app:
    container_name: garage-app
    image: spyrosmoux/garage-backend:latest
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:8081
    restart: always
    networks:
      garage-net:

networks:
  garage-net: