---
- name: Deploy Garage Project in k8s
  hosts: localhost

  tasks:
    - name: Start Docker Services
      command: docker compose -f /home/devops/garage-project-docker/docker-compose-services-k8s.yaml up -d

    - name: Deploy Helm Charts
      command: helmfile --file /home/devops/garage-project-k8s/helm/helmfile.yaml -e azure apply