---
- name: Deploy Garage Project in k8s
  hosts: localhost

  tasks:
    - name: Start Docker Services
      command: docker compose -f /home/devops/garage-project-docker/docker-compose-services.yaml up -d

    - name: Deploy Helm Charts
      command: helmfile --file /home/devops/helm/helmfile.yaml -e azure apply