apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  realm.json: |-
{{ .Files.Get "garage-project-realm.json" | indent 4}}